server.port: 8862

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: baeldungt
#          uri: baeldung.com
#          predicates:
#            - Path=//baeldung/**
#        - id: user-api
#          uri: localhost:8081/user-api
#          predicates:
#            - Path=//user-api/**